### ISSUE TITLE
[I] Replace color picker library with app's own color picker

### ISSUE THREAD

**Issue by therealbluepandabear** [therealbluepandabear/PixaPencil_Classic#227]
Try to create app's own color picker to reduce dependencies on other libraries.

**Comment by Noitarud** [comment]
After some thought (while editing #261), hues and shades to black should be offered in one control, and decided whitening is like interferance and so should deduct from first selection and add white with a separate control. I could go further and say the interference could be coloured, and the observer could be looking through a filter.

**Comment by Noitarud** [comment]
Do you think two palette adjustments on the drawing screen will work? One line for the palette hues (colours/white) and another line to select palette brightnesses (or instead of whitening or blackening select any off-white tone to mix* with the first).

The reason is if i want to add 24 hues with 4-8 brightnesses each, my palette will be rather long, but if i set it up with a hue interval and a brightness interval, the palette would be organised. Some may want a long palette if they have a small screen.

* mixing type may need to be customised, if drawing a waterfall you may like to subtract the first equally and add the second colour. Or if looking through glass you may need to only subtract the first unequally according to the second chosen.
